# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "list.cafe"
  port = 8912
  apiUrl = "/api" # You can customize graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths
  includeEnvironmentVariables = [
    "DEVELOPER_EMAIL",
    "RESEND_API_KEY",
    "AMAZON_ASSOCIATE_ID",
    "NODE_ENV",
    "GOOGLE_MAKERSUITE_API_KEY",
    "GCP_PROJECT_ID",
    "GCP_CLIENT_EMAIL",
    "GCP_PRIVATE_KEY",
    "GCP_BUCKET_ID"
    # Add any ENV vars that should be available to the web side to this array
    # See https://redwoodjs.com/docs/environment-variables#web
  ]
[api]
  port = 8913
[browser]
  open = false
[notifications]
  versionUpdates = ["latest"]
