import type { Prisma, Address } from '@prisma/client'
import type { ScenarioData } from '@redwoodjs/testing/api'

export const standard = defineScenario<Prisma.AddressCreateArgs>({
  address: {
    one: {
      data: {
        administrativeArea: 'String',
        alternativeAdministrativeArea: 'String',
        alternativeLocality: 'String',
        alternativeProvince: 'String',
        buildingName: 'String',
        buildingNumber: 'String',
        companyName: 'String',
        countryName: 'String',
        departmentName: 'String',
        dependentLocality: 'String',
        dependentStreetName: 'String',
        dependentStreetSuffix: 'String',
        doubleDependentLocality: 'String',
        levelName: 'String',
        line1: 'String',
        line2: 'String',
        line3: 'String',
        line4: 'String',
        line5: 'String',
        locality: 'String',
        postOfficeBoxNumber: 'String',
        postOfficeReference1: 'String',
        postOfficeReference2: 'String',
        postalCode: 'String',
        province: 'String',
        provinceCode: 'String',
        provinceName: 'String',
        streetName: 'String',
        streetSuffix: 'String',
        subBuildingName: 'String',
        unitName: 'String',
      },
    },
    two: {
      data: {
        administrativeArea: 'String',
        alternativeAdministrativeArea: 'String',
        alternativeLocality: 'String',
        alternativeProvince: 'String',
        buildingName: 'String',
        buildingNumber: 'String',
        companyName: 'String',
        countryName: 'String',
        departmentName: 'String',
        dependentLocality: 'String',
        dependentStreetName: 'String',
        dependentStreetSuffix: 'String',
        doubleDependentLocality: 'String',
        levelName: 'String',
        line1: 'String',
        line2: 'String',
        line3: 'String',
        line4: 'String',
        line5: 'String',
        locality: 'String',
        postOfficeBoxNumber: 'String',
        postOfficeReference1: 'String',
        postOfficeReference2: 'String',
        postalCode: 'String',
        province: 'String',
        provinceCode: 'String',
        provinceName: 'String',
        streetName: 'String',
        streetSuffix: 'String',
        subBuildingName: 'String',
        unitName: 'String',
      },
    },
  },
})

export type StandardScenario = ScenarioData<Address, 'address'>
