-- CreateTable
CREATE TABLE "ListTag" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "note" TEXT,
    "tagId" INTEGER NOT NULL,
    "addedByUserId" INTEGER,

    CONSTRAINT "ListTag_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ListTag" ADD CONSTRAINT "ListTag_tagId_fkey" FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ListTag" ADD CONSTRAINT "ListTag_addedByUserId_fkey" FOREIGN KEY ("addedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
